version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    container_name: magaz_api
    ports:
      - "8080:8080"
    networks:
      - shop_network

networks:
  shop_network:
    driver: bridge