api:
  version: "v1"

env: "dev"

server:
  host: "localhost"
  port: 8081
  timeout_ms: 4s
  idle_timeout_ms: 60s

redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 10
    min_idle_conns: 1
    max_conn_age: 0
    pool_timeout: 4s
    idle_timeout: 5m
    idle_check_frequency: 1m

database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  user: "gans"
  password: "Steelfree"
  name: "shop"
  sslmode: "disable"    # disable, require, verify-ca, verify-full
  max_open_conns: 10                  # Maximum number of open connections to the database
  max_idle_conns: 5                   # Maximum number of idle connections in the pool
  conn_max_lifetime: "30m"            # Maximum amount of time a connection may be reused


tg_bot:
  token: "7466095384:AAEg1aQpK6vbp0AWodLGbPALCVhHlKY1_kM"
  webhook_link: "https://d607-73-192-67-43.ngrok-free.app"
  webhook_path: "/api/bot/telegram"


