states:
  - name: start
    transitions:
      - event: "start"
        to: "order"
  - name: order
    transitions:
      - event: "order"
        to: "city"
  - name: city
    transitions:
      - event: "city"
        to: "product"
  - name: product
    transitions:
      - event: "product"
        to: "quantity"
  - name: quantity
    transitions:
      - event: "quantity"
        to: "payment"
  - name: payment
    transitions:
      - event: "payment"
        to: "conformation"
  - name: conformation
    transitions:
      - event: "conformation"
        to: "final"
  - name: final
    transitions:
      - event: "final"
        to: "start"

handlers:
  - event: "start"
    handler: "StartHandler"
  - event: "order"
    handler: "OrderHandler"
  - event: "city"
    handler: "CityHandler"
  - event: "product"
    handler: "ProductHandler"
  - event: "quantity"
    handler: "QuantityHandler"
  - event: "payment"
    handler: "PaymentHandler"
  - event: "conformation"
    handler: "ConformationHandler"
  - event: "final"
    handler: "FinalHandler"
